env:
  commonjs: true
  es6: true
  node: true
extends: google
parserOptions:
  ecmaVersion: 2018
rules:
  max-len:
    - error
    - code: 120
  require-jsdoc:
    - off
  linebreak-style: off
  no-trailing-spaces: off
  arrow-parens: off
  object-curly-spacing:
    - warn
    - always
    - objectsInObjects: false
      arraysInObjects: false
